'use strict';

var tree = require('../').prototype;

module.exports = function (t, a) {
	var conf;
	a.throws(function () { t({}); }, TypeError);
	a.throws(function () { t(undefined, tree); }, TypeError);
	a.throws(function () { t(null, tree); }, TypeError);
	a.throws(function () { t('', tree); }, TypeError);
	conf = {};
	a(t(conf, tree), conf);
	conf._foo = 'bar';
	a(t(conf, tree), conf);
	conf.bar = 'foo';
	a.throws(function () { t(conf, tree); }, TypeError);
	delete conf.bar;
	conf['foo bar'] = function () {};
	a.throws(function () { t(conf, tree); }, TypeError);
	delete conf['foo bar'];
	conf.bar = function () {};
	a(t(conf, tree), conf);
	conf.elo = { class: 'raz' };
	a.throws(function () { t(conf, tree); }, TypeError);
	conf.elo.class = {};
	a(t(conf, tree), conf);
	conf.elo.content = '';
	a.throws(function () { t(conf, tree); }, TypeError);
	conf.elo.content = {};
	a.throws(function () { t(conf, tree); }, TypeError);
	conf.elo.content = function () {};
	a(t(conf, tree), conf);
	conf.elo.prepend = function () {};
	a.throws(function () { t(conf, tree); }, TypeError);
	delete conf.elo.prepend;
	conf.elo.append = function () {};
	a.throws(function () { t(conf, tree); }, TypeError);
	delete conf.elo.content;
	a(t(conf, tree), conf);
	conf.elo.prepend = function () {};
	a(t(conf, tree), conf);
};
