'use strict';

module.exports = function (t, a) {
	var conf;
	a.throws(function () { t(); }, TypeError);
	a.throws(function () { t(null); }, TypeError);
	a.throws(function () { t(''); }, TypeError);
	conf = {};
	a(t(conf), conf);
	conf._foo = 'bar';
	a(t(conf), conf);
	conf.bar = 'foo';
	a.throws(function () { t(conf); }, TypeError);
	delete conf.bar;
	conf['foo bar'] = function () {};
	a.throws(function () { t(conf); }, TypeError);
	delete conf['foo bar'];
	conf.bar = function () {};
	a(t(conf), conf);
	conf.elo = { class: 'raz' };
	a.throws(function () { t(conf); }, TypeError);
	conf.elo.class = {};
	a(t(conf), conf);
	conf.elo.content = '';
	a.throws(function () { t(conf); }, TypeError);
	conf.elo.content = {};
	a.throws(function () { t(conf); }, TypeError);
	conf.elo.content = function () {};
	a(t(conf), conf);
	conf.elo.prepend = function () {};
	a.throws(function () { t(conf); }, TypeError);
	delete conf.elo.prepend;
	conf.elo.append = function () {};
	a.throws(function () { t(conf); }, TypeError);
	delete conf.elo.content;
	a(t(conf), conf);
	conf.elo.prepend = function () {};
	a(t(conf), conf);
};
