sudo: false # http://docs.travis-ci.com/user/workers/container-based-infrastructure/
language: node_js
node_js:
  - 4
  - 5

notifications:
  email:
    - medikoo+site-tree@medikoo.com

script: "npm test && npm run lint"
